FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
EXPOSE 8080

# Assuming Store.Infrastructure is in a sibling directory to where the Dockerfile is.
COPY ["./Store.Infrastructure/*.csproj", "./Store.Infrastructure/"]
# Copy the main project's csproj file
COPY *.csproj ./

# Restore dependencies for both projects
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Store.API.dll"]